#!/usr/bin/python3

import bz2
from getpass import getpass
import hashlib
import os
import platform
import requests
import sys
import subprocess
import stat
import time

PATCH_MANIFEST = 'https://cdn.toontownrewritten.com/content/patchmanifest.txt'
CONTENT_MIRROR = 'https://download.toontownrewritten.com/patches/'
LOGIN_API = 'https://www.toontownrewritten.com/api/login?format=json'
RELEASE_NOTES_API = 'https://www.toontownrewritten.com/api/releasenotes?format=json'
STATUS_API = 'https://www.toontownrewritten.com/api/status?format=json'
HEADERS = {'Content-Type': 'application/x-www-form-urlencoded'}

OPTION_ENABLE_LOGGING = False
OPTION_USERNAME = None
OPTION_PASSWORD = None

def display_help():
    print("usage: {} [-l|--enable-logging] [-u|--username username] [-p|--password password]".format(sys.argv[0]))
    print("\t-l, --enable-logging  Allows the game to print log output to the console.")
    print("")
    print("\t-u, --username        Your account username. Requires -p/--password to be used.")
    print("\t-p, --password        Your account password. Requires -u/--username to be used.")
    print("")
    print("\t-h, --help            Displays this help message and exits.")

def get_json_response_from_get_request(api_url, data=None, headers=HEADERS):
    try:
        response = requests.get(api_url, data=data, headers=headers)
        if response.status_code != 200:
            print("error: Could not connect to Toontown Rewritten's API. (error {})".format(response.status_code))
            os._exit(1)
    except:
        print("error: Could not connect to Toontown Rewritten's API.")
        os._exit(1)

    return response.json()

def get_json_response_from_post_request(api_url, data=None, headers=HEADERS):
    try:
        response = requests.post(api_url, data=data, headers=headers)
        if response.status_code != 200:
            print("error: Could not connect to Toontown Rewritten's API. (error {})".format(response.status_code))
            os._exit(1)
    except:
        print("error: Could not connect to Toontown Rewritten's API.")
        os._exit(1)

    return response.json()

def get_latest_game_version():
    release_list = get_json_response_from_get_request(RELEASE_NOTES_API)
    latest_version = release_list[0]["slug"]
    return latest_version

def get_sha1_hash(filename):
    BLOCK_SIZE = 65536
    hasher = hashlib.sha1()
    with open(filename, 'rb') as afile:
        buf = afile.read(BLOCK_SIZE)
        while len(buf) > 0:
            hasher.update(buf)
            buf = afile.read(BLOCK_SIZE)

    result = hasher.hexdigest()
    return result

def update_file(filename, manifest):
    if os.path.isfile(filename):
        if get_sha1_hash(filename) != manifest[filename]["hash"]:
            print("updating {}...".format(filename))
            file = requests.get(CONTENT_MIRROR + manifest[filename]["dl"], headers=HEADERS)
            with open(filename + '.bz2', 'wb') as zipped:
                zipped.write(file.content)
            with open(filename, 'wb') as newfile, open(filename + '.bz2', 'rb') as zipped:
                newfile.write(bz2.decompress(zipped.read()))
            os.remove(filename + ".bz2")
    else:
        print("downloading {}...".format(filename))
        file = requests.get(CONTENT_MIRROR + manifest[filename]["dl"], headers=HEADERS)
        with open(filename + '.bz2', 'wb') as zipped:
            zipped.write(file.content)
        with open(filename, 'wb') as newfile, open(filename + '.bz2', 'rb') as zipped:
            newfile.write(bz2.decompress(zipped.read()))
        os.remove(filename + ".bz2")

def get_files_for_operating_system(manifest, operating_system):
    os_name_dict = {'Windows': 'win64', 'Darwin': 'darwin', 'Linux': 'linux'}
    files = []
    for filename in manifest:
        for system in manifest[filename]["only"]:
            if system == os_name_dict[operating_system]:
                files.append(filename)
                break
    return files

def check_for_updates():
    print("checking for game updates...")

    latest_version = get_latest_game_version()
    print("latest game version is {}".format(latest_version))

    manifest = get_json_response_from_get_request(PATCH_MANIFEST)

    operating_system = platform.system()
    files = get_files_for_operating_system(manifest, operating_system)

    for file in files:
        update_file(file, manifest)

    if operating_system == 'Linux':
        os.chmod('TTREngine', os.stat('TTREngine').st_mode | stat.S_IEXEC | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    elif operating_system == 'Darwin':
        os.chmod('Toontown Rewritten', os.stat('Toontown Rewritten').st_mode | stat.S_IEXEC | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

def login():
    details = {'username': username, 'password': password}

    response = get_json_response_from_post_request(LOGIN_API, details)

    if response["success"] == "false":
        print("login failed: {}".format(response["banner"]))
        os._exit(1)

    elif response["success"] == "delayed":
        print("game entrance delay detected")
        print("the server should have you ready to go in {} seconds.".format(response["eta"]))
        delay(response["queueToken"])

    elif response["success"] == "partial":
        print("enter the ToonGuard code that was just emailed to you.")
        guard = input("> ")
        auth_details = {'appToken': guard, 'authToken': response['responseToken']}
        response = get_json_response_from_post_request(LOGIN_API, auth_details)

        if response["success"] == "true":
            launch(response["cookie"], response["gameserver"])
        elif response["success"] == "delayed":
            print("game entrance delay detected")
            print("the server should have you ready to go in {} seconds.".format(response["eta"]))
            delay(response["queueToken"])
        else:
            print("login failed: {}".format(response["banner"]))
            os._exit(1)

    elif response["success"] == "true":
        launch(response["cookie"], response["gameserver"])

def launch(cookie, server):
    print("you're good to go. launching the game...")
    os.environ['TTR_PLAYCOOKIE'] = cookie
    os.environ['TTR_GAMESERVER'] = server

    if platform.system() == 'Windows':
        subprocess.call('TTREngine64.exe', stdout=subprocess.DEVNULL if not OPTION_ENABLE_LOGGING else None,
                                           stderr=subprocess.STDOUT if not OPTION_ENABLE_LOGGING else None)
    elif platform.system() == 'Darwin':
        subprocess.call('./Toontown Rewritten', stdout=subprocess.DEVNULL if not OPTION_ENABLE_LOGGING else None,
                                                stderr=subprocess.STDOUT if not OPTION_ENABLE_LOGGING else None)
    elif platform.system() == 'Linux':
        subprocess.call('./TTREngine', stdout=subprocess.DEVNULL if not OPTION_ENABLE_LOGGING else None,
                                       stderr=subprocess.STDOUT if not OPTION_ENABLE_LOGGING else None)
    else:
        print("{} is unsupported, sorry :(".format(platform.system()))
        os._exit(1)

    print("game closed, exiting the launcher...")

def delay(token):
    details = {'username': username, 'password': password, 'queueToken': token}
    delayed = True
    while delayed:
        time.sleep(2)
        print("still trying...")
        response = get_json_response_from_post_request(LOGIN_API, details)
        if response["success"] == "true":
            launch(response["cookie"], response["gameserver"])
            delayed = False
        else:
            print("launch failed: {}".format(response["banner"]))
            os._exit(1)

if __name__ == "__main__":
    print("ttr-linux-cli by reindeer-cafe, tgsm\n")

    # arg parsing
    for i in range(len(sys.argv)):
        # Displays usage information and exits
        if sys.argv[i] == "-h" or sys.argv[i] == "--help":
            display_help()
            os._exit(0)

        elif sys.argv[i] == "-u" or sys.argv[i] == "--username":
            try:
                OPTION_USERNAME = sys.argv[i + 1]
            except IndexError:
                print("error: -u/--username was passed, but no actual username was given.\n")
                display_help()
                os._exit(1)

        elif sys.argv[i] == "-p" or sys.argv[i] == "--password":
            try:
                OPTION_PASSWORD = sys.argv[i + 1]
            except IndexError:
                print("error: -p/--password was passed, but no actual password was given.\n")
                display_help()
                os._exit(1)

        elif sys.argv[i] == "-l" or sys.argv[i] == "--enable-logging":
            OPTION_ENABLE_LOGGING = True

    game_status = get_json_response_from_get_request(STATUS_API)
    if game_status["open"] != True:
        print(game_status["banner"])
        os._exit(1)

    check_for_updates()
    print("game is up to date!\n")

    if not OPTION_USERNAME and not OPTION_PASSWORD:
        username = input("username: ")
        password = getpass("password: ")
    else:
        username = OPTION_USERNAME
        password = OPTION_PASSWORD

    login()
